name: theSecretChat
description: A lightweight and private chat app.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  animated_text_kit: ^1.3.1
  cupertino_icons: ^0.1.2
  firebase_core: ^0.4.1+5
  firebase_auth: ^0.14.0+9
  cloud_firestore: ^0.12.10
  modal_progress_hud: ^0.1.3
  rflutter_alert: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
  - images/
